# Generated by Django 4.1.2 on 2022-11-14 23:53

from django.db import migrations
def create_data(apps, schema_editor):
    JobPosting = apps.get_model('careerly', 'JobPosting')
    JobPosting(jobtitle="Software Engineer", company="Amazon", location = "Sunnyvale, CA", jobType = "Full-time", datePosted = "2022-08-09", posting = "Blah blah blah").save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
