# Generated by Django 4.1.2 on 2022-11-13 03:00

from django.db import migrations

def create_data(apps, schema_editor):
    JobPosting = apps.get_model('careerly', 'JobPosting')
    JobPosting(jobtitle="Software Engineer", company="Amazon").save()


class Migration(migrations.Migration):

    dependencies = [
        ('careerly', '0002_rename_careerly_jobposting'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
