# Generated by Django 4.1.2 on 2022-11-14 04:16

from django.db import migrations


def create_data(apps, schema_editor):
    JobPosting = apps.get_model('careerly', 'JobPosting')
    JobPosting(jobtitle="Software Engineer", company="Amazon").save()
    JobPosting(jobtitle="Software Engineer", company="Meta").save()


class Migration(migrations.Migration):

    dependencies = [
        ('careerly', '0003_careerly'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
